/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        /**
         * Upload one or more documents
         * @description Answers immediately with a tracking id per file; indexing continues in the background.
         */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search indexed documents
         * @description Quoted phrases, `or` between alternatives and a leading minus to exclude a word are all understood. Only documents that finished indexing are ever returned.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the original file
         * @description Served inline so the browser renders it in place.
         */
        get: operations["file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a document's body
         * @description Chunks in order, paged by a cursor over chunkIndex.
         */
        get: operations["content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Accepted upload. Indexing continues in the background. */
        UploadAcceptedResponse: {
            items?: components["schemas"]["UploadedDocumentResponse"][];
        };
        /** @description Tracking handle for one accepted file */
        UploadedDocumentResponse: {
            /** Format: uuid */
            id?: string;
            filename?: string;
            /** @enum {string} */
            status?: "PROCESANDO" | "INDEXADO" | "ERROR";
        };
        /** @description One matching document with its best fragment */
        SearchHitResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /**
             * @description The title with every matched word wrapped in the U+27E6 and U+27E7 sentinels
             * @example Guia de ⟦despliegue⟧
             */
            titleHighlight?: string;
            author?: string;
            /** @enum {string} */
            category?: "MANUAL" | "SPECIFICATION" | "ARCHITECTURE_GUIDE" | "OTHER";
            tags?: string[];
            version?: string;
            /** Format: date-time */
            indexedAt?: string;
            /**
             * Format: int32
             * @description Index of the chunk the fragment came from, so the viewer can scroll to it
             */
            chunkIndex?: number;
            /**
             * Format: int32
             * @description Page the fragment came from, for documents that have pages
             */
            page?: number;
            heading?: string;
            /** @description Matched fragment, with the same sentinels as the title */
            snippet?: string;
            /** Format: double */
            rank?: number;
        };
        /** @description One page of search results, highest ranked first */
        SearchResponse: {
            items?: components["schemas"]["SearchHitResponse"][];
            /**
             * Format: int64
             * @description Documents matching the query and the filters, not chunks
             */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /**
             * Format: int64
             * @description How long the engine took, excluding rendering this response
             */
            tookMs?: number;
        };
        /** @description One page of documents, newest first */
        DocumentPageResponse: {
            items?: components["schemas"]["DocumentResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        /** @description A document and everything known about it */
        DocumentResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            author?: string;
            /** @enum {string} */
            category?: "MANUAL" | "SPECIFICATION" | "ARCHITECTURE_GUIDE" | "OTHER";
            tags?: string[];
            version?: string;
            originalFilename?: string;
            mimeType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** @enum {string} */
            status?: "PROCESANDO" | "INDEXADO" | "ERROR";
            /**
             * @description Why indexing failed, absent while the document is healthy
             * @enum {string}
             */
            errorCode?: "PDF_NO_TEXT_LAYER" | "UNSUPPORTED_FORMAT" | "CORRUPT_FILE" | "EMPTY_CONTENT" | "PROCESSING_FAILED";
            errorMessage?: string;
            /** Format: int32 */
            pageCount?: number;
            /** Format: int32 */
            chunkCount?: number;
            /** Format: int64 */
            processingMs?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            indexedAt?: string;
        };
        /** @description One slice of a document's body */
        DocumentChunkResponse: {
            /** Format: int32 */
            chunkIndex?: number;
            /** Format: int32 */
            page?: number;
            heading?: string;
            content?: string;
        };
        /** @description A window over a document's chunks, paged by a cursor over chunkIndex */
        DocumentContentResponse: {
            chunks?: components["schemas"]["DocumentChunkResponse"][];
            /**
             * Format: int32
             * @description Cursor for the next window, absent when the document ends here
             */
            nextChunkIndex?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentPageResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    files: string[];
                    metadata: string;
                };
            };
        };
        responses: {
            /** @description Accepted; every file is now PROCESANDO */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadAcceptedResponse"];
                };
            };
            /** @description A file exceeds the configured maximum size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadAcceptedResponse"];
                };
            };
            /** @description The batch was rejected; nothing was stored */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadAcceptedResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /**
                 * @description Words or quoted phrases to look for
                 * @example indice invertido -borrador
                 */
                q?: string;
                page?: number;
                pageSize?: number;
                category?: "MANUAL" | "SPECIFICATION" | "ARCHITECTURE_GUIDE" | "OTHER";
                author?: string;
                /** @description Every tag given must be present on the document */
                tags?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of ranked matches with highlighted fragments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
            /** @description The query carries no searchable term, or the paging is out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
            /** @description The search exceeded its time budget and was cancelled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    content: {
        parameters: {
            query?: {
                fromChunkIndex?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentContentResponse"];
                };
            };
        };
    };
}
